name: Deploy to Cloud Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Update package-lock.json
        run: npm install --package-lock-only

      - name: Fix vulnerabilities
        run: npm audit fix

      - name: Log environment information
        run: |
          node -v
          npm -v
          echo $PATH
          ls -la

      - name: Build project
        run: npm run build

      - name: List build directory
        run: ls -la oj

      - name: Check file permissions
        run: ls -la oj

      - name: Print working directory
        run: pwd

      - name: List all files
        run: ls -la

      - name: Print environment variables
        run: printenv

      - name: Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'oj/*'
          target: '/www/www***/doj.littlejh.cn'
          debug: true
